# Generated by Django 3.0.5 on 2020-05-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
