# Generated by Django 3.0.5 on 2020-05-02 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0007_auto_20200502_1527'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('topic', 'text', 'date_added')},
        ),
    ]
