# Generated by Django 3.0.5 on 2020-05-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0008_auto_20200502_1545'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('topic', 'text', 'id')},
        ),
    ]
